--테이블 삭제
DROP TABLE LEVELGRADE;
DROP TABLE CUSTOMER;

-- 테이블 생성
CREATE TABLE LEVELGRADE(
    LNO     NUMBER(1) PRIMARY KEY,
    LNAME VARCHAR2(20) NOT NULL,
    LOW     NUMBER(10),
    HIGH     NUMBER(10)   );

CREATE TABLE CUSTOMER(
    CID         NUMBER(10) PRIMARY KEY,
    CNAME    VARCHAR2(20) NOT NULL,
    CTEL        VARCHAR2(20) NOT NULL,
    CPOINT    NUMBER(8) DEFAULT 1000,
    CAMOUNT NUMBER(10) DEFAULT 0,
    LNO  NUMBER(1) DEFAULT 0 REFERENCES LEVELGRADE(LNO)    );
    
-- 시퀀스 생성
CREATE SEQUENCE CUSTOMER_CID_SEQ MAXVALUE 9999999999 NOCACHE NOCYCLE;
DROP SEQUENCE CUSTOMER_CID_SEQ;

-- 레벨 입력
INSERT INTO LEVELGRADE(LNO, LNAME) VALUES (-1, '블랙');
INSERT INTO LEVELGRADE VALUES (0, '일반', 0, 1000000);
INSERT INTO LEVELGRADE VALUES (1, '실버', 1000001, 5000000);
INSERT INTO LEVELGRADE VALUES (2, '골드', 5000001, 20000000);
INSERT INTO LEVELGRADE VALUES (3, 'VIP', 20000001, 100000000);
INSERT INTO LEVELGRADE VALUES (4, 'VVIP', 100000001, 9999999999);

SELECT * FROM LEVELGRADE;


-- 더미 데이터 입력
INSERT INTO CUSTOMER(CID, CNAME, CTEL) 
    VALUES (CUSTOMER_CID_SEQ.NEXTVAL, '홍길동', '010-5555-5555');
INSERT INTO CUSTOMER(CID, CNAME, CTEL) 
    VALUES (CUSTOMER_CID_SEQ.NEXTVAL, '유길동', '010-5555-6666');
INSERT INTO CUSTOMER(CID, CNAME, CTEL, LNO) 
    VALUES (CUSTOMER_CID_SEQ.NEXTVAL, '유길동', '010-5555-7777', -1);
SELECT * FROM CUSTOMER;
COMMIT;
-- 레벨이름 검색
SELECT LNAME FROM LEVELGRADE;

SELECT HIGH - CAMOUNT NEEDPAY FROM CUSTOMER C, LEVELGRADE L WHERE C.LNO+1=L.LNO AND C.LNO!=-1 AND CID = 2;

-- CID로 검색
SELECT CID, CNAME, CTEL, CPOINT, CAMOUNT, LNAME, 
    (SELECT HIGH - CAMOUNT FROM CUSTOMER C, LEVELGRADE L WHERE C.LNO+1=L.LNO AND C.LNO!=-1 AND CID = CS.CID) NEEDPAY
    FROM CUSTOMER CS, LEVELGRADE LG
    WHERE CS.LNO=LG.LNO AND CS.CID=1;

-- 폰 뒤 4자리 검색
SELECT CTEL, CNAME, CPOINT, CAMOUNT, L2.LNAME, NVL(TO_CHAR(L.HIGH-CAMOUNT), '블랙회원입니다') NEEDPAY 
    FROM CUSTOMER C, LEVELGRADE L, LEVELGRADE L2
    WHERE C.LNO+1=L.LNO AND C.LNO=L2.LNO AND CTEL LIKE '%7777';
    
-- 고객이름 검색
SELECT CTEL, CNAME, CPOINT, CAMOUNT, L2.LNAME, NVL(L.HIGH-CAMOUNT, -1) NEEDPAY 
    FROM CUSTOMER C, LEVELGRADE L, LEVELGRADE L2
    WHERE C.LNO+1=L.LNO AND C.LNO=L2.LNO AND CNAME = '홍길동';
    
-- 포인트로만 구매
UPDATE CUSTOMER
    SET CPOINT = CPOINT-1000
    WHERE CNAME = '홍길동';
 
 -- 물품구매
 UPDATE CUSTOMER
    SET CAMOUNT = CAMOUNT + 1000001,
          CPOINT = CPOINT + 1000001*0.05,
          LNO = (SELECT L.LNO FROM CUSTOMER C, LEVELGRADE L WHERE CAMOUNT + 1000001 BETWEEN LOW AND HIGH AND CID = 1)
    WHERE CID = 1;


-- 등급별 출력
SELECT L2.LNAME, CID, CTEL, CNAME, CPOINT, CAMOUNT, NVL(L.HIGH-CAMOUNT, -1) NEEDPAY 
    FROM CUSTOMER C, LEVELGRADE L, LEVELGRADE L2
    WHERE C.LNO+1=L.LNO AND C.LNO=L2.LNO AND L2.LNAME = '실버'
    ORDER BY L2.LNAME DESC;

-- 전체 출력
SELECT CID, CTEL, CNAME, CPOINT, CAMOUNT, L2.LNAME, NVL(L.HIGH-CAMOUNT, -1) NEEDPAY 
    FROM CUSTOMER C, LEVELGRADE L, LEVELGRADE L2
    WHERE C.LNO+1=L.LNO AND C.LNO=L2.LNO
    ORDER BY CAMOUNT DESC;
    
-- 회원가입
INSERT INTO CUSTOMER(CID, CNAME, CTEL) 
    VALUES (CUSTOMER_CID_SEQ.NEXTVAL, '김유진', '010-2587-2448');
    
-- 번호 수정
UPDATE CUSTOMER
    SET CTEL = '010-0000-0000'
    WHERE CID = 1;
    
-- 회원탈퇴
DELETE FROM CUSTOMER WHERE CTEL = '010-2587-2448';

COMMIT;