DROP TABLE FRIEND;
DROP SEQUENCE FRIEND_SEQ;

CREATE TABLE FRIEND(
    FNUM NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(30) NOT NULL
);

CREATE SEQUENCE FRIEND_SEQ MAXVALUE 99999 NOCACHE NOCYCLE;

INSERT INTO FRIEND (FNUM, NAME, PHONE)
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', '010-9999-9999');

COMMIT;

SELECT * FROM FRIEND;
    
SELECT * FROM FRIEND WHERE NAME LIKE '%'||'홍'||'%' AND  PHONE LIKE   '%'||'9999'||'%';
