-- EX1. 사용자에게 부서번호 입력받아 부서 정보 뿌리기
SELECT * FROM DEPT WHERE DEPTNO=30;

-- EX2. 
SELECT * FROM DEPT WHERE DEPTNO=30;
    -- 해당부서번호 사원(사번, 이름, 급여, 상사명)의 정보
SELECT W.EMPNO, W.ENAME , W.SAL, M.ENAME MANAGER
    FROM EMP W, EMP M
    WHERE W.MGR=M.EMPNO AND W.DEPTNO=30;

-- EX3
SELECT * FROM DEPT WHERE DNAME = UPPER('SALES');
-- 해당 부서 사원(사번, 이름, 급여, 급여등급)을 출력
SELECT EMPNO, ENAME, SAL, GRADE
    FROM EMP E, SALGRADE, DEPT D
    WHERE SAL BETWEEN LOSAL AND HISAL 
    AND E.DEPTNO=D.DEPTNO 
    AND DNAME= UPPER('SALES');

SELECT EMPNO, ENAME, SAL, GRADE
    FROM EMP , SALGRADE
    WHERE SAL BETWEEN LOSAL AND HISAL 
    AND E.DEPTNO=D.DEPTNO
    AND DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME=UPPER('SALES'))