-- 테이블/시퀀스 생성
DROP SEQUENCE CUSTOMER_SEQ;
DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMER(
    CNO     NUMBER(5) PRIMARY KEY,
    CNAME VARCHAR2(30) NOT NULL,
    CTEL    VARCHAR(20) NOT NULL,
    CPOINT NUMBER(8) DEFAULT 1000 CHECK(CPOINT>=0)  );

CREATE SEQUENCE CUSTOMER_SEQ
    MAXVALUE 99999
    NOCACHE
    NOCYCLE;
    
-- 더미데이터 입력
INSERT INTO CUSTOMER(CNO, CNAME, CTEL)
    VALUES (CUSTOMER_SEQ.NEXTVAL, '홍길동', '010-1111-1111');
INSERT INTO CUSTOMER(CNO, CNAME, CTEL)
    VALUES (CUSTOMER_SEQ.NEXTVAL, '김길동', '010-1111-1111');
INSERT INTO CUSTOMER(CNO, CNAME, CTEL)
    VALUES (CUSTOMER_SEQ.NEXTVAL, '서길동', '010-2222-2222');
INSERT INTO CUSTOMER(CNO, CNAME, CTEL)
    VALUES (CUSTOMER_SEQ.NEXTVAL, '홍길동', '010-3333-3333');
    
-- 가입
INSERT INTO CUSTOMER(CNO, CNAME, CTEL)
    VALUES (CUSTOMER_SEQ.NEXTVAL, '홍길동', '010-3333-3333');

-- 폰 뒷자리 조회
SELECT CNAME, CTEL, CPOINT
    FROM CUSTOMER
    WHERE CTEL LIKE '%'||'2222';

-- 출력
SELECT CNAME, CTEL, CPOINT
    FROM CUSTOMER;