-- EX1. 사용자에게 부서번호 입력받아 부서 정보 뿌리기
SELECT * FROM DEPT WHERE DEPTNO=30;
-- EX2
SELECT * FROM DEPT;
-- EX3
DELETE FROM DEPT WHERE DEPTNO=90;

SELECT EMPNO, ENAME, JOB, SAL 
    FROM EMP E, DEPT D
    WHERE E.DEPTNO=D.DEPTNO AND DNAME = UPPER('abd');
UPDATE DEPT  SET DNAME = UPPER(DNAME);
UPDATE DEPT  SET DNAME = TRIM(DNAME);
COMMIT;