--DROP
DROP TABLE BOARD;
DROP SEQUENCE BOARD_SEQ;


-- CREATE
CREATE TABLE BOARD(
    BID             NUMBER(6)          PRIMARY KEY,
    BNAME        VARCHAR2(50)     NOT NULL, -- 작성자 이름
    BTITLE         VARCHAR2(100)    NOT NULL,
    BCONTENT   VARCHAR2(1000),
    BDATE         DATE                  DEFAULT SYSDATE NOT NULL, -- 작성일
    BHIT            NUMBER(6)          DEFAULT 0 NOT NULL,
    BGROUP       NUMBER(6)          NOT NULL,
    BSTEP          NUMBER(6)          NOT NULL,
    BINDENT      NUMBER(6)          NOT NULL,
    BIP              VARCHAR2(20)     NOT NULL);
    
CREATE SEQUENCE BOARD_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;


-- DUMMY DATA
SELECT * FROM BOARD;
INSERT INTO BOARD 
    (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES(BOARD_SEQ.NEXTVAL, '홍길동', '글1', '-', BOARD_SEQ.CURRVAL, 0, 0, '192.168.10.30');
INSERT INTO BOARD 
    (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES(BOARD_SEQ.NEXTVAL, '김길동', '글2', '-', BOARD_SEQ.CURRVAL, 0, 0, '192.168.10.31');
-- 1번글의 답변 DUMMY
INSERT INTO BOARD 
    (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES(BOARD_SEQ.NEXTVAL, '김길동', '글1-1', '-', 1, 1, 1, '192.168.10.31');
COMMIT;

-- DAO에 들어갈 QUERY
-- 전체 글 갯수
SELECT COUNT(*) CNT FROM BOARD;

-- 글 리스트
SELECT * 
    FROM (SELECT ROWNUM RN, A.*
                    FROM (SELECT * FROM BOARD ORDER BY BGROUP DESC, BSTEP) A )
    WHERE RN BETWEEN 1 AND 2;
    
-- 원글 작성하기
INSERT INTO BOARD 
    (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES(BOARD_SEQ.NEXTVAL, '홍길동', '글1', '-', BOARD_SEQ.CURRVAL, 0, 0, '192.168.10.30');

-- BID로 조회수 올리기
UPDATE BOARD SET BHIT = BHIT+1 WHERE BID = 1;

-- BID로 글 상세보기
SELECT * FROM BOARD WHERE BID = 1;

-- 답변글 작성하기
    -- 이전 스텝
    UPDATE BOARD 
        SET  BSTEP = BSTEP+1
        WHERE BGROUP = 1 AND BSTEP > 0;
    -- 답변글 작성
    INSERT INTO BOARD 
        (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
        VALUES(BOARD_SEQ.NEXTVAL, '김길동', '글1-3', '-', 1, 1, 1, '192.168.10.31');
        
-- 글 수정하기
UPDATE BOARD 
    SET BNAME = '김김김',
         BTITLE = '수정된 글1',
         BCONTENT = '수정된 글내용',
         BIP = '192.1.1.1'
    WHERE BID = 1;
    
-- 글삭제하기
DELETE FROM BOARD WHERE BID = 2;

-- 자기의 답변글까지 같이 지우기
SELECT 
DELETE FROM BOARD
  WHERE BID=136 OR   
            BGROUP = (SELECT *
                            FROM BOARD B, (SELECT * FROM BOARD WHERE BID=136) A
                            WHERE B.BGROUP=A.BGROUP) AND
            BSTEP >= (SELECT MIN(B.BSTEP)
                            FROM BOARD B, (SELECT * FROM BOARD WHERE BID=136) A
                            WHERE B.BGROUP=A.BGROUP AND B.BSTEP>A.BSTEP AND B.BINDENT>A.BINDENT) AND
            BINDENT >= (SELECT MIN(B.BINDENT)
                                FROM BOARD B, (SELECT * FROM BOARD WHERE BID=136) A
                                WHERE B.BGROUP=A.BGROUP AND B.BSTEP>A.BSTEP AND B.BINDENT>A.BINDENT);
COMMIT;